<?php

namespace App\Console\Commands;

use App\Enums\CardBatchPdfAction;
use App\Enums\CardStatus;
use App\Enums\CardTemplate;
use App\Enums\FlashMessage;
use App\Enums\MembershipRole;
use App\Enums\OrganizationStatus;
use App\Enums\TransactionType;
use Illuminate\Console\Attributes\Description;
use Illuminate\Console\Attributes\Signature;
use Illuminate\Console\Command;
use Illuminate\Support\Facades\File;

/**
 * Writes the PHP enums the frontend maps to words as TypeScript string unions,
 * so resources/js/lib/flash.ts and lib/labels.ts can key EXHAUSTIVE Records off
 * them: add a case in PHP, run this, and `npm run types:check` fails until the
 * words exist.
 *
 * A small generator rather than a package: a few enums of string cases need
 * nothing more. `--check` exits 1 when the file is stale (a Pest test runs it).
 */
#[Signature('types:enums {--check : Fail if the generated file is out of date}')]
#[Description('Export PHP enums to resources/js/types/enums.generated.ts')]
class ExportEnumTypes extends Command
{
    /**
     * @var array<string, class-string<\BackedEnum>>
     */
    public const ENUMS = [
        'CardBatchPdfAction' => CardBatchPdfAction::class,
        'CardStatus' => CardStatus::class,
        'CardTemplate' => CardTemplate::class,
        'FlashMessage' => FlashMessage::class,
        'MembershipRole' => MembershipRole::class,
        'OrganizationStatus' => OrganizationStatus::class,
        'TransactionType' => TransactionType::class,
    ];

    public const PATH = 'js/types/enums.generated.ts';

    public function handle(): int
    {
        $path = resource_path(self::PATH);
        $contents = self::render();

        if ($this->option('check')) {
            if (! File::exists($path) || File::get($path) !== $contents) {
                $this->error('resources/'.self::PATH.' is out of date. Run `php artisan types:enums`.');

                return self::FAILURE;
            }

            $this->info('resources/'.self::PATH.' is up to date.');

            return self::SUCCESS;
        }

        File::put($path, $contents);
        $this->info('Wrote resources/'.self::PATH.'.');

        return self::SUCCESS;
    }

    public static function render(): string
    {
        $out = "// Generated by `php artisan types:enums` from app/Enums. Do not edit.\n";

        foreach (self::ENUMS as $name => $enum) {
            $values = array_map(
                fn (\BackedEnum $case): string => "    | '".addslashes((string) $case->value)."'",
                $enum::cases(),
            );

            $out .= "\n/** {$enum} */\nexport type {$name} =\n".implode("\n", $values).";\n";
        }

        return $out;
    }
}
