// AUTO-GENERATED by `php artisan i18n:manifest`. Do not edit.
//
// Laravel's translatable strings, declared to duckalization's extractor
// so PHP and TypeScript share ONE catalog, one brief and one review. The
// extractor parses TypeScript only; this is how the 63 messages
// Laravel renders (validation refusals, ledger errors, the CSV header,
// the offline page) get counted, briefed and translated with the UI.
//
// The comment above each call is the PHP source location, which is what
// a translator sees in the brief.
//
// NOTHING IMPORTS THIS FILE, so it never reaches a bundle. phpMessages()
// is never called: the extractor needs to SEE the calls, not run them.
//
// Placeholders here are Laravel's `:name`, not duckalization's `{name}`.
// They are literal text to the catalog and must be kept verbatim.
//
// To regenerate: php artisan i18n:manifest
import { __ } from '@/i18n';

export function phpMessages(): string[] {
    return [
        // resources/views/mail/card-link.blade.php:11
        __(':business sent you a gift card'),
        // app/Actions/Fortify/CreateNewUser.php:67
        __(':name\'s Business'),
        // app/Exceptions/CardBatchException.php:35
        __('A batch can have at most :max cards.'),
        // app/Exceptions/CardBatchException.php:30
        __('A batch needs at least one card.'),
        // app/Http/Controllers/Dashboard/CardLinkController.php:51
        __('A cancelled card cannot be sent.'),
        // app/Exceptions/LedgerException.php:44
        __('A note is required for adjustments.'),
        // app/Http/Controllers/Dashboard/CardLinkController.php:57
        __('Activate this card before sending it.'),
        // app/Enums/TransactionType.php:33
        __('Adjustment'),
        // app/Http/Controllers/Dashboard/TransactionController.php:70
        __('Amount'),
        // app/Http/Controllers/PublicCardController.php:103
        __('An email is already saved for this card.'),
        // app/Http/Requests/Admin/StoreOrganizationRequest.php:57
        __('An organization with this slug already exists.'),
        // app/Http/Controllers/Dashboard/TransactionController.php:71
        __('Balance after'),
        // app/Http/Controllers/Dashboard/TransactionController.php:68
        __('Card'),
        // app/Http/Controllers/Reader/ScanController.php:45
        __('Card not found.'),
        // app/Enums/TransactionType.php:32
        __('Charge'),
        // app/Http/Controllers/Dashboard/TransactionController.php:67
        __('Date'),
        // app/Exceptions/LedgerException.php:29
        __('Enter an amount with up to two decimals.'),
        // app/Actions/Fortify/CreateNewUser.php:53
        __('Gift Card'),
        // app/Exceptions/LedgerException.php:49
        __('Insufficient balance.'),
        // app/Support/PackageMessages.php:42
        __('Invalid credential format.'),
        // app/Enums/TransactionType.php:31
        __('Load'),
        // app/Http/Controllers/Dashboard/TransactionController.php:72
        __('Note'),
        // app/Exceptions/CardBatchException.php:55
        __('Only a card that is not activated yet can be voided.'),
        // app/Http/Controllers/Dashboard/CardController.php:216
        __('Only a frozen card can be unfrozen.'),
        // app/Http/Controllers/Dashboard/CardController.php:199
        __('Only an active card can be frozen.'),
        // resources/views/mail/card-link.blade.php:27
        __('Open your card'),
        // app/Support/PackageMessages.php:43
        __('Passkey registration session expired. Please try again.'),
        // app/Support/PackageMessages.php:44
        __('Passkey verification session expired. Please try again.'),
        // app/Http/Controllers/Dashboard/TransactionController.php:73
        __('Performed by'),
        // app/Enums/TransactionType.php:34
        __('Refund'),
        // app/Http/Controllers/Dashboard/CardLinkController.php:63
        __('Save a cardholder email first.'),
        // resources/views/mail/card-link.blade.php:40
        __('Show the code on that page when you pay. Keep this email: anyone with the link can use the card.'),
        // app/Exceptions/LedgerException.php:39
        __('The adjustment cannot be 0.'),
        // app/Exceptions/LedgerException.php:54
        __('The adjustment would leave a negative balance.'),
        // app/Exceptions/LedgerException.php:34
        __('The amount must be greater than 0.'),
        // app/Exceptions/LedgerException.php:59
        __('The balance cannot be more than :max.'),
        // app/Http/Requests/Settings/UpdateOrganizationSettingsRequest.php:59
        __('The brand color must be a hex color such as #1e40af.'),
        // app/Http/Controllers/Admin/SuperadminController.php:53
        __('The last superadmin cannot be revoked. Grant the role to someone else first.'),
        // app/Http/Controllers/Dashboard/SettingsController.php:117
        __('The logo could not be stored.'),
        // app/Support/PackageMessages.php:40
        __('The provided password was incorrect.'),
        // app/Support/PackageMessages.php:38
        __('The provided two factor authentication code was invalid.'),
        // app/Support/PackageMessages.php:39
        __('The provided two factor recovery code was invalid.'),
        // resources/views/offline.blade.php:46
        __('The reader needs an internet connection to look up cards and post charges. Check your connection and try again.'),
        // app/Exceptions/CardBatchException.php:50
        __('This batch is already voided.'),
        // app/Exceptions/CardBatchException.php:40
        __('This business can hold at most :limit cards in stock. There is room for :room more.'),
        // app/Exceptions/CardBatchException.php:45
        __('This business has no active program to issue cards from.'),
        // app/Exceptions/CardBatchException.php:60
        __('This business is suspended. Contact support.'),
        // app/Exceptions/LedgerException.php:79
        __('This card is already activated.'),
        // app/Exceptions/LedgerException.php:69
        __('This card is cancelled.'),
        // app/Exceptions/LedgerException.php:64
        __('This card is frozen.'),
        // app/Exceptions/LedgerException.php:74
        __('This card is not activated yet.'),
        // app/Providers/AppServiceProvider.php:62
        __('This card was emailed several times in the last hour. Try again later.'),
        // app/Http/Controllers/Admin/OrganizationController.php:280
        __('This organization is already active.'),
        // app/Http/Controllers/Admin/OrganizationController.php:281
        __('This organization is already suspended.'),
        // app/Http/Controllers/Admin/OrganizationController.php:282
        __('This organization is cancelled.'),
        // app/Providers/AppServiceProvider.php:56
        __('Too many attempts. Please try again in a minute.'),
        // resources/views/offline.blade.php:50
        __('Try again'),
        // app/Http/Controllers/Dashboard/TransactionController.php:69
        __('Type'),
        // app/Http/Requests/Admin/StoreOrganizationRequest.php:56
        __('Use only lowercase letters, numbers, and single hyphens.'),
        // resources/views/offline.blade.php:25
        __('You are offline'),
        // app/Exceptions/LedgerException.php:84
        __('You have reached your plan limit of :limit cards. Contact support to raise the limit.'),
        // app/Mail/CardLinkMail.php:30
        __('Your :business gift card'),
        // resources/views/mail/card-link.blade.php:14
        __('Your balance is :balance.'),
    ];
}
