// AUTO-GENERATED by `php artisan i18n:manifest`. Do not edit.
//
// Laravel's translatable strings, declared to duckalization's extractor
// so PHP and TypeScript share ONE catalog, one brief and one review. The
// extractor parses TypeScript only; this is how the 47 messages
// Laravel renders (validation refusals, ledger errors, the CSV header,
// the offline page) get counted, briefed and translated with the UI.
//
// The comment above each call is the PHP source location, which is what
// a translator sees in the brief.
//
// NOTHING IMPORTS THIS FILE, so it never reaches a bundle. phpMessages()
// is never called: the extractor needs to SEE the calls, not run them.
//
// Placeholders here are Laravel's `:name`, not duckalization's `{name}`.
// They are literal text to the catalog and must be kept verbatim.
//
// To regenerate: php artisan i18n:manifest
import { __ } from '@/i18n';

export function phpMessages(): string[] {
    return [
        // app/Actions/Fortify/CreateNewUser.php:67
        __(':name\'s Business'),
        // app/Exceptions/LedgerException.php:44
        __('A note is required for adjustments.'),
        // app/Enums/TransactionType.php:33
        __('Adjustment'),
        // app/Http/Controllers/Dashboard/TransactionController.php:70
        __('Amount'),
        // app/Http/Controllers/PublicCardController.php:66
        __('An email is already saved for this card.'),
        // app/Http/Requests/Admin/StoreOrganizationRequest.php:56
        __('An organization with this slug already exists.'),
        // app/Http/Controllers/Dashboard/TransactionController.php:71
        __('Balance after'),
        // app/Http/Controllers/Dashboard/TransactionController.php:68
        __('Card'),
        // app/Http/Controllers/Reader/ScanController.php:45
        __('Card not found.'),
        // app/Enums/TransactionType.php:32
        __('Charge'),
        // app/Http/Controllers/Dashboard/TransactionController.php:67
        __('Date'),
        // app/Exceptions/LedgerException.php:29
        __('Enter an amount with up to two decimals.'),
        // app/Actions/Fortify/CreateNewUser.php:53
        __('Gift Card'),
        // app/Exceptions/LedgerException.php:49
        __('Insufficient balance.'),
        // app/Support/PackageMessages.php:42
        __('Invalid credential format.'),
        // app/Enums/TransactionType.php:31
        __('Load'),
        // app/Http/Controllers/Dashboard/TransactionController.php:72
        __('Note'),
        // app/Http/Controllers/Dashboard/CardController.php:205
        __('Only a frozen card can be unfrozen.'),
        // app/Http/Controllers/Dashboard/CardController.php:188
        __('Only an active card can be frozen.'),
        // app/Support/PackageMessages.php:43
        __('Passkey registration session expired. Please try again.'),
        // app/Support/PackageMessages.php:44
        __('Passkey verification session expired. Please try again.'),
        // app/Http/Controllers/Dashboard/TransactionController.php:73
        __('Performed by'),
        // app/Enums/TransactionType.php:34
        __('Refund'),
        // app/Exceptions/LedgerException.php:39
        __('The adjustment cannot be 0.'),
        // app/Exceptions/LedgerException.php:54
        __('The adjustment would leave a negative balance.'),
        // app/Exceptions/LedgerException.php:34
        __('The amount must be greater than 0.'),
        // app/Exceptions/LedgerException.php:59
        __('The balance cannot be more than :max.'),
        // app/Http/Requests/Settings/UpdateOrganizationSettingsRequest.php:59
        __('The brand color must be a hex color such as #1e40af.'),
        // app/Http/Controllers/Admin/SuperadminController.php:53
        __('The last superadmin cannot be revoked. Grant the role to someone else first.'),
        // app/Http/Controllers/Dashboard/SettingsController.php:117
        __('The logo could not be stored.'),
        // app/Support/PackageMessages.php:40
        __('The provided password was incorrect.'),
        // app/Support/PackageMessages.php:38
        __('The provided two factor authentication code was invalid.'),
        // app/Support/PackageMessages.php:39
        __('The provided two factor recovery code was invalid.'),
        // resources/views/offline.blade.php:46
        __('The reader needs an internet connection to look up cards and post charges. Check your connection and try again.'),
        // app/Http/Controllers/Dashboard/CardController.php:125
        __('This business has no active program to issue cards from.'),
        // app/Exceptions/LedgerException.php:74
        __('This business is suspended. Contact support.'),
        // app/Exceptions/LedgerException.php:69
        __('This card is cancelled.'),
        // app/Exceptions/LedgerException.php:64
        __('This card is frozen.'),
        // app/Http/Controllers/Admin/OrganizationController.php:256
        __('This organization is already active.'),
        // app/Http/Controllers/Admin/OrganizationController.php:257
        __('This organization is already suspended.'),
        // app/Http/Controllers/Admin/OrganizationController.php:258
        __('This organization is cancelled.'),
        // app/Providers/AppServiceProvider.php:52
        __('Too many attempts. Please try again in a minute.'),
        // resources/views/offline.blade.php:50
        __('Try again'),
        // app/Http/Controllers/Dashboard/TransactionController.php:69
        __('Type'),
        // app/Http/Requests/Admin/StoreOrganizationRequest.php:55
        __('Use only lowercase letters, numbers, and single hyphens.'),
        // resources/views/offline.blade.php:25
        __('You are offline'),
        // app/Http/Controllers/Dashboard/CardController.php:115
        __('You have reached your plan limit of :limit cards. Contact support to raise the limit.'),
    ];
}
