// Generated by `php artisan types:enums` from app/Enums. Do not edit.

/** App\Enums\CardStatus */
export type CardStatus =
    | 'inactive'
    | 'active'
    | 'frozen'
    | 'depleted'
    | 'cancelled';

/** App\Enums\FlashMessage */
export type FlashMessage =
    | 'card.created'
    | 'card.frozen'
    | 'card.unfrozen'
    | 'card.email_saved'
    | 'card.link_sent'
    | 'card.voided'
    | 'batch.created'
    | 'batch.voided'
    | 'ledger.loaded'
    | 'ledger.charged'
    | 'ledger.activated'
    | 'ledger.adjusted'
    | 'settings.business_saved'
    | 'settings.program_saved'
    | 'settings.profile_updated'
    | 'settings.password_updated'
    | 'public_card.email_saved'
    | 'organization.switched'
    | 'organization.not_writable'
    | 'admin.organization_created_new_owner'
    | 'admin.organization_created_existing_owner'
    | 'admin.plan_saved'
    | 'admin.organization_suspended'
    | 'admin.organization_reactivated'
    | 'admin.temporary_password_set'
    | 'admin.superadmin_claimed'
    | 'admin.superadmin_granted'
    | 'admin.superadmin_revoked';

/** App\Enums\MembershipRole */
export type MembershipRole =
    | 'owner'
    | 'manager'
    | 'employee';

/** App\Enums\OrganizationStatus */
export type OrganizationStatus =
    | 'active'
    | 'suspended'
    | 'cancelled';

/** App\Enums\TransactionType */
export type TransactionType =
    | 'load'
    | 'spend'
    | 'adjustment'
    | 'refund';
